[build]
  command = "apt-get update && apt-get install -y python3-dev build-essential && python3 -m pip install -r requirements.txt && python3 app.py"
  publish = "build"

[functions]
  [functions.python]
    version = "3.11"
    external_node_modules = []
